<a href="https://colab.research.google.com/github/juliuswasajja/ml-zoomcamp/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Creating arrays

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,6.3)

array([6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3])

## Create array from a list

In [ ]:
a = np.array([1,3,4,5,7])

### Accessing elements

In [ ]:
a[3]

5

In [ ]:
np.arange(2,10,.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [ ]:
np.linspace(3,4,10)

array([3.        , 3.11111111, 3.22222222, 3.33333333, 3.44444444,
       3.55555556, 3.66666667, 3.77777778, 3.88888889, 4.        ])

## Multidimensional Array

In [ ]:
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array ([
        [1,2,3],
         [4,5,6],
         [7,8,9]
])

In [ ]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n[1,1] = 40

In [ ]:
n

array([[ 1,  2,  3],
       [ 4, 40,  6],
       [ 7,  8,  9]])

In [ ]:
n[1]

array([ 4, 40,  6])

In [ ]:
n[:,2] = [10,20,30]

In [ ]:
n

array([[ 1,  2, 10],
       [ 4, 40, 20],
       [ 7,  8, 30]])

In [ ]:
np.random.seed(3)
np.random.rand(3,3) * 100

array([[55.07979026, 70.81478226, 29.09047389],
       [51.08276052, 89.29469543, 89.62930889],
       [12.55853105, 20.72428781,  5.14672033]])

In [ ]:
np.random.seed(3)
np.random.randn(3,3) * 100

array([[ 178.86284734,   43.65098505,    9.64974681],
       [-186.34927034,  -27.73882025,  -35.47589793],
       [  -8.27414815,  -62.70006768,   -4.3818169 ]])

In [ ]:
np.random.seed(3)
np.random.randint(low=10,high=100, size=(3,3))

array([[34, 13, 66],
       [82, 10, 31],
       [29, 84, 51]])

In [ ]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

### Element wise operations

In [ ]:
b

array([0, 1, 2, 3, 4])

In [ ]:
a = np.array([12, 13, 14, 15, 16])
a

array([12, 13, 14, 15, 16])

In [ ]:
b*a

array([ 0, 13, 28, 45, 64])

### Comparison elements

In [ ]:
(a >= 13.5)

array([False, False,  True,  True,  True])

In [ ]:
b > a

array([False, False, False, False, False])

In [ ]:
a[ a>= 13.5]

array([14, 15, 16])

### Summarizing operations

In [ ]:
b.min()

0

In [ ]:
a.std()

1.4142135623730951